### PR TITLE
Add datastore interface and restructure files

### PR DESCRIPTION
**Pull request by michaelliu2**

### CODE REVIEW

**Comment by michaelliu2** [comment]
@ianlofs @hdahme Adding an interface for datastores.  Also making file structure more reasonable

**Comment by michaelliu2** [comment]
@katekligman

**Comment by ianlofs** [comment]
@michaelliu2  👍 the renaming from db_credentials to credentials makes sense too, especially since we will be using this for the salesforce loader most likely?

**Comment by michaelliu2** [comment]
@ianlofs yup, trying to use better naming.  Not everything is a "database" per se.

**Pull request merged**
